In [7]:
import numpy as np
import tensorflow as tf

In [22]:
bandits = [5, 0, -0.2, -5]
num_bandits = len(bandits)
def pullBandit(bandit):
    result = np.random.randn(1)
    if result < bandit:
        return 1
    else:
        return -1

In [23]:
tf.reset_default_graph()

weights = tf.Variable(tf.ones([num_bandits]),name='weights')
chosen_action = tf.argmax(weights,0)
reward_holder = tf.placeholder(shape=[1],dtype=tf.float32,name='reward_holder')
action_holder = tf.placeholder(shape=[1],dtype=tf.int32,name='action_holder')

resposible_weight = tf.slice(weights,action_holder,[1])
loss = -(tf.log(resposible_weight)*reward_holder)
grad = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [24]:
log = tf.summary.FileWriter('./log',graph=tf.get_default_graph())

In [33]:
total_episodes = 1000
total_reward = np.zeros(num_bandits)
e = 0.1

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    i = 0
    while i < total_episodes:
        if np.random.rand() < e:
            action = np.random.randint(num_bandits)
        else:
            action = sess.run(chosen_action)
            
        reward = pullBandit(bandits[action])
        g,r,w = sess.run([grad,resposible_weight,weights],
                         feed_dict={reward_holder:[reward],
                                    action_holder:[action]})
        total_reward[action] += reward
        if i % 50 == 0:
            print sess.run(weights)
        i+=1

[ 1.00100005  1.          1.          1.        ]
[ 1.0488317   1.          0.99900001  1.        ]
[ 1.09274375  1.          0.99799901  0.99799901]
[ 1.13319266  0.99900001  0.99900204  0.996997  ]
[ 1.17139161  1.00000107  0.99700004  0.99599397]
[ 1.20589662  0.99699807  0.99900508  0.99197173]
[ 1.24588108  0.99599504  0.99900508  0.99197173]
[ 1.28306222  0.99699908  0.99900508  0.98995453]
[ 1.31843662  0.99699908  0.99900609  0.98793322]
[ 1.35288608  0.99599606  0.99700308  0.98692101]
[ 1.38720083  0.9970001   0.99700308  0.98489344]
[ 1.41998172  0.99599707  0.99800611  0.9828617 ]
[ 1.45202291  0.99800414  0.99700409  0.98184425]
[ 1.48134756  0.99800515  0.99600106  0.97776395]
[ 1.51208818  0.99700314  0.99600208  0.97674119]
[ 1.54221606  0.99499607  0.99700612  0.97571737]
[ 1.57303846  0.99399102  0.99600309  0.97571737]
[ 1.60077095  0.99399203  0.99499905  0.97263944]
[ 1.63109958  0.99399203  0.993994    0.97263944]
[ 1.65966952  0.9949981   0.993994    0.97058213]


In [13]:
import tensorflow as tf
import tensorflow.contrib.slim as slim
import numpy as np

In [32]:
class contextual_bandit():
    def __init__(self):
        self.state = 0
        self.bandits = np.array([[0.2,0,-0,-5],[0.1,-5,1,0.25],[-5,5,5,5]])
        self.num_bandits = self.bandits.shape[0]
        self.num_actions = self.bandits.shape[1]
    
    def getBandit(self):
        self.state = np.random.randint(0,len(self.bandits))
        return self.state
    
    def pullArm(self,action):
        bandit = self.bandits(self.state,action)
        result = np.random.randn(1)
        if result > bandit:
            return 1
        else:
            return -1
        
class agent():
    def __init__(self,)